version: '2'

services:

  postgres:
    restart: always
    image: postgres:latest
    build: database
    volumes:
         - /var/lib/postgresql
    ports:
      - 54322:5432

  product-service:
    restart: always
    build: python
    volumes:
      - ./python:/usr/src/app
    ports:
      - 5555:80
    depends_on:
      - postgres

  website:
    image: php:apache
    volumes: 
      - ./website:/var/www/html
    ports:
      - 5556:80
    depends_on:
      - product-service
